### PR TITLE
Add initialLoad options

### PR DESCRIPTION
**Pull request by hoantran-it**
First of all, I want to say thank you for creating this awesome library, it makes my UI become more beautiful and flexible. During using time, I find out that we should have to add more options to improve it. 

This PR adds an option to on/off initial load at the first time. If we always have initial load by default, some time it will load two page at the first time. For example in my case, it load page 1 and page 2 at the first time and sometime result of page 2 return before page 1, the mismatch occur.

image

Please help to review my pr and tell me if we can improve it someway.

Thanks!

### CODE REVIEW

**Comment by hoantran-it** [comment]
@skoob13 Please help to take a look on this pr and do not hesitate to tell me if it has any problem. Thanks!

**Comment by mfferreira** [comment]
bump

**Comment by scmarlatt** [comment]
I'm also experiencing the same issue but instead its calling loadMore 5ish times. Any update?

**Comment by skoob13** [comment]
Thanks for PR! Sorry for a long review.

**Pull request merged**
